// 30 professional resume templates inspired by Overleaf CV gallery styles
// Each template defines layout structure, fonts, color scheme, and section rendering

const templates = [
  {
    id: 'classic-professional',
    name: 'Classic Professional',
    category: 'Professional',
    description: 'Traditional single-column layout with serif fonts. Ideal for corporate roles.',
    preview: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    style: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      headerBg: '#1a1a2e',
      headerText: '#ffffff',
      accentColor: '#1a1a2e',
      bodyFont: "'Georgia', serif",
      sectionBorder: '2px solid #1a1a2e',
    },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'Modern',
    description: 'Clean minimalist design with sans-serif typography and ample whitespace.',
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    style: {
      fontFamily: "'Helvetica Neue', Arial, sans-serif",
      headerBg: '#ffffff',
      headerText: '#2d3748',
      accentColor: '#667eea',
      bodyFont: "'Helvetica Neue', sans-serif",
      sectionBorder: '2px solid #667eea',
    },
  },
  {
    id: 'executive-blue',
    name: 'Executive Blue',
    category: 'Executive',
    description: 'Bold navy header with gold accents. Perfect for senior leadership.',
    preview: 'linear-gradient(135deg, #0c2461 0%, #1e3799 100%)',
    style: {
      fontFamily: "'Cambria', Georgia, serif",
      headerBg: '#0c2461',
      headerText: '#ffffff',
      accentColor: '#0c2461',
      bodyFont: "'Cambria', serif",
      sectionBorder: '3px solid #0c2461',
    },
  },
  {
    id: 'tech-modern',
    name: 'Tech Modern',
    category: 'Technology',
    description: 'Developer-friendly layout with monospace accents and a tech aesthetic.',
    preview: 'linear-gradient(135deg, #00b894 0%, #00cec9 100%)',
    style: {
      fontFamily: "'SF Mono', 'Fira Code', monospace",
      headerBg: '#2d3436',
      headerText: '#00b894',
      accentColor: '#00b894',
      bodyFont: "'Inter', sans-serif",
      sectionBorder: '2px solid #00b894',
    },
  },
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    category: 'Creative',
    description: 'Vibrant design with bold colors for designers and creatives.',
    preview: 'linear-gradient(135deg, #e17055 0%, #fdcb6e 100%)',
    style: {
      fontFamily: "'Poppins', sans-serif",
      headerBg: '#e17055',
      headerText: '#ffffff',
      accentColor: '#e17055',
      bodyFont: "'Poppins', sans-serif",
      sectionBorder: '3px solid #e17055',
    },
  },
  {
    id: 'academic-cv',
    name: 'Academic CV',
    category: 'Academic',
    description: 'Structured layout for researchers with publication and grant sections.',
    preview: 'linear-gradient(135deg, #2c3e50 0%, #34495e 100%)',
    style: {
      fontFamily: "'Computer Modern', 'Latin Modern', Georgia, serif",
      headerBg: '#ffffff',
      headerText: '#2c3e50',
      accentColor: '#2c3e50',
      bodyFont: "'Georgia', serif",
      sectionBorder: '1px solid #2c3e50',
    },
  },
  {
    id: 'sidebar-elegant',
    name: 'Sidebar Elegant',
    category: 'Modern',
    description: 'Two-column layout with a colored sidebar for contact and skills.',
    preview: 'linear-gradient(135deg, #6c5ce7 0%, #a29bfe 100%)',
    style: {
      fontFamily: "'Lato', sans-serif",
      headerBg: '#6c5ce7',
      headerText: '#ffffff',
      accentColor: '#6c5ce7',
      bodyFont: "'Lato', sans-serif",
      sectionBorder: '2px solid #6c5ce7',
      layout: 'sidebar',
    },
  },
  {
    id: 'swiss-design',
    name: 'Swiss Design',
    category: 'Modern',
    description: 'Grid-based layout inspired by Swiss/International typographic style.',
    preview: 'linear-gradient(135deg, #e74c3c 0%, #c0392b 100%)',
    style: {
      fontFamily: "'Helvetica', 'Arial', sans-serif",
      headerBg: '#ffffff',
      headerText: '#e74c3c',
      accentColor: '#e74c3c',
      bodyFont: "'Helvetica', sans-serif",
      sectionBorder: '4px solid #e74c3c',
    },
  },
  {
    id: 'deedy-resume',
    name: 'Deedy Resume',
    category: 'Technology',
    description: 'Popular two-column tech resume. Compact and information-dense.',
    preview: 'linear-gradient(135deg, #333333 0%, #666666 100%)',
    style: {
      fontFamily: "'Lato', sans-serif",
      headerBg: '#ffffff',
      headerText: '#333333',
      accentColor: '#333333',
      bodyFont: "'Lato', sans-serif",
      sectionBorder: '1px solid #333333',
      layout: 'two-column',
    },
  },
  {
    id: 'jake-resume',
    name: 'Jake\'s Resume',
    category: 'Technology',
    description: 'Ultra-clean single-column tech resume focused on bullet points.',
    preview: 'linear-gradient(135deg, #2b5876 0%, #4e4376 100%)',
    style: {
      fontFamily: "'Roboto', sans-serif",
      headerBg: '#ffffff',
      headerText: '#000000',
      accentColor: '#2b5876',
      bodyFont: "'Roboto', sans-serif",
      sectionBorder: '1px solid #000000',
    },
  },
  {
    id: 'alta-cv',
    name: 'AltaCV',
    category: 'Modern',
    description: 'Infographic-style resume with skill bars and icon-based sections.',
    preview: 'linear-gradient(135deg, #3d5a80 0%, #98c1d9 100%)',
    style: {
      fontFamily: "'Lato', sans-serif",
      headerBg: '#3d5a80',
      headerText: '#ffffff',
      accentColor: '#3d5a80',
      bodyFont: "'Lato', sans-serif",
      sectionBorder: '2px solid #3d5a80',
      layout: 'sidebar',
    },
  },
  {
    id: 'awesome-cv',
    name: 'Awesome CV',
    category: 'Professional',
    description: 'Feature-rich CV with colored section headers and clean typography.',
    preview: 'linear-gradient(135deg, #00838f 0%, #00acc1 100%)',
    style: {
      fontFamily: "'Source Sans Pro', sans-serif",
      headerBg: '#ffffff',
      headerText: '#00838f',
      accentColor: '#00838f',
      bodyFont: "'Source Sans Pro', sans-serif",
      sectionBorder: '2px solid #00838f',
    },
  },
  {
    id: 'moderncv-classic',
    name: 'ModernCV Classic',
    category: 'Academic',
    description: 'LaTeX ModernCV inspired with timeline-style experience entries.',
    preview: 'linear-gradient(135deg, #4a69bd 0%, #6a89cc 100%)',
    style: {
      fontFamily: "'Latin Modern', Georgia, serif",
      headerBg: '#ffffff',
      headerText: '#4a69bd',
      accentColor: '#4a69bd',
      bodyFont: "'Georgia', serif",
      sectionBorder: '0px',
      layout: 'timeline',
    },
  },
  {
    id: 'moderncv-banking',
    name: 'ModernCV Banking',
    category: 'Executive',
    description: 'Formal CV style suited for finance and banking professionals.',
    preview: 'linear-gradient(135deg, #1B1464 0%, #0a3d62 100%)',
    style: {
      fontFamily: "'Garamond', 'Times New Roman', serif",
      headerBg: '#1B1464',
      headerText: '#ffffff',
      accentColor: '#1B1464',
      bodyFont: "'Garamond', serif",
      sectionBorder: '2px solid #1B1464',
    },
  },
  {
    id: 'hipster-cv',
    name: 'Hipster CV',
    category: 'Creative',
    description: 'Unconventional creative layout with sidebar photo area and bold type.',
    preview: 'linear-gradient(135deg, #f39c12 0%, #e74c3c 100%)',
    style: {
      fontFamily: "'Josefin Sans', sans-serif",
      headerBg: '#f39c12',
      headerText: '#ffffff',
      accentColor: '#f39c12',
      bodyFont: "'Open Sans', sans-serif",
      sectionBorder: '3px solid #f39c12',
      layout: 'sidebar',
    },
  },
  {
    id: 'elegant-resume',
    name: 'Elegant Resume',
    category: 'Professional',
    description: 'Sophisticated design with subtle color accents and refined typography.',
    preview: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)',
    style: {
      fontFamily: "'Cormorant Garamond', Georgia, serif",
      headerBg: '#2c3e50',
      headerText: '#ecf0f1',
      accentColor: '#2c3e50',
      bodyFont: "'Open Sans', sans-serif",
      sectionBorder: '1px solid #bdc3c7',
    },
  },
  {
    id: 'friggeri-cv',
    name: 'Friggeri CV',
    category: 'Modern',
    description: 'Colorful sidebar with muted body. A modern classic from Overleaf.',
    preview: 'linear-gradient(135deg, #74b9ff 0%, #0984e3 100%)',
    style: {
      fontFamily: "'Helvetica Neue', sans-serif",
      headerBg: '#2d3436',
      headerText: '#ffffff',
      accentColor: '#0984e3',
      bodyFont: "'Helvetica Neue', sans-serif",
      sectionBorder: '2px solid #0984e3',
      layout: 'sidebar',
    },
  },
  {
    id: 'developer-cv',
    name: 'Developer CV',
    category: 'Technology',
    description: 'Tech-focused sidebar layout with skills matrix and project highlights.',
    preview: 'linear-gradient(135deg, #0f9b0f 0%, #44bd32 100%)',
    style: {
      fontFamily: "'Fira Sans', sans-serif",
      headerBg: '#1e272e',
      headerText: '#0f9b0f',
      accentColor: '#0f9b0f',
      bodyFont: "'Fira Sans', sans-serif",
      sectionBorder: '2px solid #0f9b0f',
      layout: 'sidebar',
    },
  },
  {
    id: 'data-science-cv',
    name: 'Data Science CV',
    category: 'Technology',
    description: 'Analytical layout highlighting technical skills, tools, and publications.',
    preview: 'linear-gradient(135deg, #6c5ce7 0%, #fd79a8 100%)',
    style: {
      fontFamily: "'IBM Plex Sans', sans-serif",
      headerBg: '#ffffff',
      headerText: '#6c5ce7',
      accentColor: '#6c5ce7',
      bodyFont: "'IBM Plex Sans', sans-serif",
      sectionBorder: '2px solid #6c5ce7',
    },
  },
  {
    id: 'compact-resume',
    name: 'Compact Resume',
    category: 'Professional',
    description: 'Dense single-page layout fitting maximum content in minimal space.',
    preview: 'linear-gradient(135deg, #636e72 0%, #b2bec3 100%)',
    style: {
      fontFamily: "'Arial Narrow', Arial, sans-serif",
      headerBg: '#ffffff',
      headerText: '#2d3436',
      accentColor: '#636e72',
      bodyFont: "'Arial Narrow', sans-serif",
      sectionBorder: '1px solid #636e72',
    },
  },
  {
    id: 'material-design',
    name: 'Material Design',
    category: 'Modern',
    description: 'Google Material-inspired with card-based sections and depth shadows.',
    preview: 'linear-gradient(135deg, #4285f4 0%, #34a853 100%)',
    style: {
      fontFamily: "'Roboto', sans-serif",
      headerBg: '#4285f4',
      headerText: '#ffffff',
      accentColor: '#4285f4',
      bodyFont: "'Roboto', sans-serif",
      sectionBorder: '0px',
    },
  },
  {
    id: 'nordic-clean',
    name: 'Nordic Clean',
    category: 'Modern',
    description: 'Scandinavian-inspired minimal design with cool tones and clean lines.',
    preview: 'linear-gradient(135deg, #dfe6e9 0%, #b2bec3 100%)',
    style: {
      fontFamily: "'Inter', sans-serif",
      headerBg: '#ffffff',
      headerText: '#2d3436',
      accentColor: '#636e72',
      bodyFont: "'Inter', sans-serif",
      sectionBorder: '1px solid #dfe6e9',
    },
  },
  {
    id: 'consulting-pro',
    name: 'Consulting Pro',
    category: 'Executive',
    description: 'McKinsey-style structured layout for management consultants.',
    preview: 'linear-gradient(135deg, #003366 0%, #004080 100%)',
    style: {
      fontFamily: "'Georgia', serif",
      headerBg: '#003366',
      headerText: '#ffffff',
      accentColor: '#003366',
      bodyFont: "'Calibri', sans-serif",
      sectionBorder: '2px solid #003366',
    },
  },
  {
    id: 'startup-modern',
    name: 'Startup Modern',
    category: 'Creative',
    description: 'Fresh, dynamic layout popular in startup and product roles.',
    preview: 'linear-gradient(135deg, #ff6b6b 0%, #feca57 100%)',
    style: {
      fontFamily: "'DM Sans', sans-serif",
      headerBg: '#ffffff',
      headerText: '#ff6b6b',
      accentColor: '#ff6b6b',
      bodyFont: "'DM Sans', sans-serif",
      sectionBorder: '3px solid #ff6b6b',
    },
  },
  {
    id: 'legal-formal',
    name: 'Legal Formal',
    category: 'Professional',
    description: 'Conservative design for legal and compliance professionals.',
    preview: 'linear-gradient(135deg, #2c2c2c 0%, #4a4a4a 100%)',
    style: {
      fontFamily: "'Book Antiqua', 'Palatino', serif",
      headerBg: '#ffffff',
      headerText: '#2c2c2c',
      accentColor: '#2c2c2c',
      bodyFont: "'Book Antiqua', serif",
      sectionBorder: '1px solid #2c2c2c',
    },
  },
  {
    id: 'healthcare-pro',
    name: 'Healthcare Pro',
    category: 'Professional',
    description: 'Clean clinical layout for medical and healthcare professionals.',
    preview: 'linear-gradient(135deg, #00b4d8 0%, #0077b6 100%)',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      headerBg: '#0077b6',
      headerText: '#ffffff',
      accentColor: '#0077b6',
      bodyFont: "'Segoe UI', sans-serif",
      sectionBorder: '2px solid #0077b6',
    },
  },
  {
    id: 'ux-designer',
    name: 'UX Designer',
    category: 'Creative',
    description: 'Portfolio-ready layout with emphasis on process and case studies.',
    preview: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)',
    style: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      headerBg: '#ffffff',
      headerText: '#a855f7',
      accentColor: '#a855f7',
      bodyFont: "'Plus Jakarta Sans', sans-serif",
      sectionBorder: '2px solid #a855f7',
      layout: 'sidebar',
    },
  },
  {
    id: 'engineering-cv',
    name: 'Engineering CV',
    category: 'Professional',
    description: 'Technical CV for mechanical, civil, and electrical engineers.',
    preview: 'linear-gradient(135deg, #e67e22 0%, #d35400 100%)',
    style: {
      fontFamily: "'Roboto Slab', serif",
      headerBg: '#d35400',
      headerText: '#ffffff',
      accentColor: '#d35400',
      bodyFont: "'Roboto', sans-serif",
      sectionBorder: '2px solid #d35400',
    },
  },
  {
    id: 'graduate-fresh',
    name: 'Graduate Fresh',
    category: 'Academic',
    description: 'Entry-level resume emphasizing education, projects, and internships.',
    preview: 'linear-gradient(135deg, #00cec9 0%, #6c5ce7 100%)',
    style: {
      fontFamily: "'Nunito', sans-serif",
      headerBg: '#6c5ce7',
      headerText: '#ffffff',
      accentColor: '#6c5ce7',
      bodyFont: "'Nunito', sans-serif",
      sectionBorder: '2px solid #6c5ce7',
    },
  },
  {
    id: 'dark-professional',
    name: 'Dark Professional',
    category: 'Modern',
    description: 'Inverted dark theme resume with light text on dark background.',
    preview: 'linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%)',
    style: {
      fontFamily: "'Inter', sans-serif",
      headerBg: '#0f0f0f',
      headerText: '#f1f1f1',
      accentColor: '#6366f1',
      bodyFont: "'Inter', sans-serif",
      sectionBorder: '1px solid #333333',
      darkMode: true,
    },
  },
]

export default templates

export const categories = [...new Set(templates.map((t) => t.category))]
